### ISSUE TITLE
Implement curry

### ISSUE THREAD

**Issue by DzyubSpirit** [metarhia/Common#10]
I think there are many occasions when `bind` is used with null first argument. Does it need implementation? And what file should it place in?

**Comment by aqrln** [comment]
But that's not currying. The first argument of `Function.prototype.bind` sets the `[[BoundThis]]` internal slot, which is effectively passed as `this` value when calling the wrapped function.

**Comment by DzyubSpirit** [comment]
@aqrln I meant occasions when `bind` is used not for that purpose but has more arguments and doesn't use `this`. Under these conditions first argument looks redundant.

**Comment by aqrln** [comment]
@DzyubSpirit so do you think `curry(fn.bind, null).call(fn, ...args)` is in any way more concise or readable than `fn.bind(null, ...args)`? I feel like I miss the point and don't understand you right.

**Comment by DzyubSpirit** [comment]
@aqrln Why does `curry(fn, ...args)` not work?

**Comment by nechaido** [comment]
@aqrln I think @DzyubSpirit  proposes:
```js
function curry(fn, ...args) {
  return fn.bind(null, ...args);
}
```
So you can use it like this:
```js
const multiply = (x, y) => x * y;
const double = curry(multiply, 2);
```
Am I right, @DzyubSpirit ?
Yet I see no reason in doing so because `common.curry(multiply, 2)` doesn't look much better then `multiply.bind(null, 2)` IMHO

**Comment by DzyubSpirit** [comment]
@nechaido, exactly

**Comment by DzyubSpirit** [comment]
@nechaido, you forgot `api.`, yeah? I think import path length is not critical. If you need several functions from `common` you probably already have had one of these statements:
```
const { ... } = app.common;
```javascript
```
const cmn = app.common;
```javascript
With those qualified imports using common functions is really short. 
I think common usages should be like that although sometimes `bind` is shorter
