### ISSUE TITLE
Add map,filter, etc. for iterators

### ISSUE THREAD

**Issue by nechaido** [metarhia/common#122]
I propose to add an `Iterator` class that has `map`, `filter`, etc. functions. Example syntax:
```js
const set = new Set([1, 2, 3, 4]);

const doubledArray = new Iterator(set)
  .map(item => item * 2)
  .fetch();

const ten = new Iterator(set)
  .reduce((previous, current) => previous + current, 0);

new Iterator(set).forEach(item => console.log(item));
```

**Comment by aqrln** [comment]
Love the idea, but shouldn't it be a part of `metasync` instead though?

**Comment by nechaido** [comment]
@aqrln `metasync` is for async functionality. I will to add `AsyncIterator` for `metasync` as soon as @tshemsedinov  approves it.
