### ISSUE TITLE
Rename module

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/common#138]
We need shorter and conceptual name for npm. Now npm module name is `metarhia-common`

**Comment by nechaido** [comment]
@tshemsedinov I personally prefer the current name.

**Comment by tshemsedinov** [comment]
@nechaido I'd like to have same names in npm and git

**Comment by tshemsedinov** [comment]
`metalib` ?

**Comment by nechaido** [comment]
@tshemsedinov sounds ok, but `@metarhia/common` is the best option IMHO.

**Comment by tshemsedinov** [comment]
@nechaido but thus we should move all libs to https://www.npmjs.com/org/metarhia

**Comment by nechaido** [comment]
@tshemsedinov I would like that.
