### ISSUE TITLE
Implement indexes for Enum

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/common#150]
Enumerated type: https://github.com/metarhia/common/blob/master/lib/enum.js

**Comment by nechaido** [comment]
@tshemsedinov we have decided that Enums must be stored as a number, so we do not need a specific indexing algorithm for them. May I close this one?

**Comment by tshemsedinov** [comment]
Yes, close please, we will store enumerated as integers in db, will never use string/char/varchar for enumerated keys.
