### ISSUE TITLE
Implement applyArgs

### ISSUE THREAD

**Issue by DzyubSpirit** [metarhia/common#19]
`applyArgs` take arguments and returns function which takes function and apply these arguments to it.
```javascript
const multy = [2, 3, 4, 5].map(x => y => (x * y));
multy.map(applyArgs(4)); // [8, 12, 16, 20]

const asyncFns = [...];
const data = { ... } ;
const callback = (...) => { ... };
asyncFns.map(applyArgs(data, callback));
```

**Comment by tshemsedinov** [comment]
Why do we need callback here? `fns.map(applyArgs(data, callback));`

**Comment by DzyubSpirit** [comment]
@tshemsedinov I mean that `fns` is array of asynchronous functions therefore callback is needed as argument. I rename `fns` to `asyncFns` for clarity.
