### ISSUE TITLE
Unobvious lib format

### ISSUE THREAD

**Issue by nechaido** [metarhia/Common#2]
IMHO, if we use namespaces - all fuctions from namespacce should be in one file. If we have a need to divide them into few logical parts - we add a corresponding namespace.. It will look like:
```
lib
|-common.js    // ~~api.common.function()
|-common
  |-data.js    // ~~api.common.data.function()
  |-id.js      // ~~api.common.id.function()
```

@tshemsedinov @aqrln @belochub what do you think about it?

**Comment by tshemsedinov** [comment]
This repository will contain just `api.common` so we need no multiple subfolders for different namespaces.

**Comment by tshemsedinov** [comment]
Modularity can be fun: http://node-machine.org/
