### ISSUE TITLE
Identity functions

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/common#205]
Functional programming classic Identity is:
```js
const id = x => x;
```
but we need async Identity, returning initial value to callback second argument:
```js
const asyncId => (x, callback) => {
  callback(null, x);
};
```
Array iteration functions contract is `(array, fn, callback)` so we need something like this:
```js
const arrayIterationId = (items, fn, callback) => {
  callback(null, items.map(id));
};
```
For example we need it here: https://github.com/metarhia/metasync/pull/379/files#diff-8359eeb9ceb67853754febf281ddb569R14

We may place all Identity implementations in `common` or place sync implementation in `common` and async implementation in `metasync`.

**Comment by tshemsedinov** [comment]
@nechaido @belochub please assign comebody

**Comment by machendos** [comment]
Should I change all the old uses of similar functions to a new implementation in ``common`` in this issue?
