### ISSUE TITLE
Implement recursive mkdir

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/common#246]
Implement recursive `mkdir`
Like this: https://www.npmjs.com/package/mkdirp
FYI: @belochub @nechaido you can assign this to new guys

**Comment by belochub** [comment]
@tshemsedinov can't we just use the `recursive` option in [`fs.mkdir()`](https://nodejs.org/docs/latest/api/fs.html#fs_fs_mkdir_path_options_callback)?

**Comment by tshemsedinov** [comment]
@belochub if so we will need polyfill for node 8 or even < v10.12.0

**Comment by belochub** [comment]
Closed via https://github.com/metarhia/common/commit/00f425efc1211a16dfa94417eb74930b4c6c1555.
