### ISSUE TITLE
Chain composition

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/common#37]
@DzyubSpirit I think to compose chain we can use following syntax:
```js
const composedChain = compose().filter(x => x > 0).map(x => x * 2).map(x => ++x);
```
And then use it:
```js
const result = composedChain(data);
```
It will be equivalent for expression/superposition:
```js
const result = data.filter(x => x > 0).map(x => x * 2).map(x => ++x);
```
But unknown `data`.
We can also do it easier:
```
const composedChain = data => data.filter(x => x > 0).map(x => x * 2).map(x => ++x);
const result = composedChain(data);
```
But in case of simple `compose` we also can do as lambda:
```
const composedFunc = x => f1(f2(x));
```
But function `compose` gives us flexibility and unification.
So chain composition may give us something interesting.
Need more examples, I think.

**Comment by DzyubSpirit** [comment]
@tshemsedinov, one more option is:
```javascript
const composedChain = compose(
  filter(x => x > 0), arr => (arr[0] = 2, arr), map(x => ++x)
);
```

**Comment by tshemsedinov** [comment]
@DzyubSpirit this syntax require `filter`, `map` and other methods visible in global context.

**Comment by DzyubSpirit** [comment]
@tshemsedinov, no, it can be used as that:
```javascript
const M = module;
const composedChain = compose(
  M.filter(x => x > 0), arr => (arr[0] = 2, arr), M.map(x => ++x)
);
```
That is harder, I agree. There is trade between complexity of getting functions from module and ability to use custom functions

**Comment by tshemsedinov** [comment]
Moved: https://github.com/metarhia/metasync/issues/274
