### ISSUE TITLE
Minimize the build time on CI

### ISSUE THREAD

**Issue by aqrln** [metarhia/Common#5]
I have enabled CI for the repo, but I haven't changed the default settings. Now each PR is built twice: as a push to a branch and as a PR itself. Now we need to consider:

1. If this repo adopts purely PR-based workflow, we may disable build on pushes completely, and, optionally, schedule nightly builds on master every 24 hours (that's how JSTP is configured).

2. If the project adopts some mixed workflow when both PRs and direct pushes to master are allowed, like Impress does, then we can leave both "build on pushes" and "build on PRs" settings turned on but whitelist branches to master only. This way all pushes to master and all the PRs will be built.

/cc @tshemsedinov

**Comment by tshemsedinov** [comment]
I'd prefer build on PR only @aqrln

**Comment by aqrln** [comment]
Perfect. Done.

What about scheduled builds of `master` branch? Do we need them here?

**Comment by tshemsedinov** [comment]
I don't know why such builds may be needed, all changes will be tested in PR builds, just some dependencies may change and break something. But as of now this module have no dependencies.

**Comment by aqrln** [comment]
Well, *theoretically*, a patch might work before a change in master, then, after a build has passed, a commit which breaks the patch in a way the patch can still be applied without conflicts lands on master, then the patch is merged. AFAIK, this problem occurs in very large projects sometimes :) Though it is unlikely to happen in such a small project, and even if it does, we just need to make sure to run `npm test` locally before pushing to master. So yeah, automated builds of `master` are more of a precaution, not a necessity.

**Comment by tshemsedinov** [comment]
What we may really do: combined integration test of Metarhia stack: Impress + JSTP + Common + Metasync + Globalstorage. After test of all components together no need to test them separately.

**Comment by aqrln** [comment]
I'm working on it :)

Though I may argue with the point that we'll no longer need to test them separately, since it is a whole lot faster for single commits. IMO such an integration test has to be run before publishing a package (i.e., if we are about to release component A, then all components C<sub>i</sub> ∈ Metarhia, C<sub>i</sub> ≠ A are taken from NPM and A is taken from Git, and they are tested together). Though these details are tbd, the integration test won't change much either way.

BTW, can you please make <ci.metarhia.com> point to `162.243.102.155`?

**Comment by tshemsedinov** [comment]
Zone file updated

**Comment by aqrln** [comment]
Great, thanks. Closing the issue since the original question is resolved. The further discussion about CI should be in https://github.com/metarhia/Metarhia/issues/5 and other appropriate threads.
