### ISSUE TITLE
Broken `git log` output

### ISSUE THREAD

**Issue by aqrln** [metarhia/Common#6]
```console
$ git log --oneline
9d815a5 test: make linting a part of the testing process PR-URL: https://github.com/metarhia/Common/pull/4 * Add `npm run lint` script that can be invoked on its own. * Run linter in the end of `npm test` script if the tests have passed.
7b13f1e lib: code style optimizations PR-URL: https://github.com/metarhia/Common/pull/3
8c4713d lib: optimize object cloning PR-URL: https://github.com/metarhia/Common/pull/1
5e7d7d3 lib: make `clone` abstract again
37f0079 Add required dependencies
6b6544f Fix namespaces export
6f07e7d Add api.common.cache (enhanced Map)
d4ceded Extract api.common from Impress
07bb9b0 Fix exports
e736df5 Library structure
1750b04 Initial commit
```

@tshemsedinov an empty line after the short commit message is **required** by Git. Without it, the whole commit description is a short message with newlines treated as spaces.

**Comment by aqrln** [comment]
Aside from that, all metadata, both built into Git (like `Signed-off-by`) and custom (like `PR-URL`) should be at the end of commit description.

**Comment by tshemsedinov** [comment]
Log fixed and `landed` links changed after rewrite

**Comment by aqrln** [comment]
Great, thanks for that. I didn't mean to rewrite the history, it was more of a warning to make it right in the next commits, but having a clean and neat history from the very beginning is awesome.

@nechaido make sure to `git pull --force` your `master` branch and rebase your local branches if you have any.
