### ISSUE TITLE
Asynchronous NOP

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/common#64]
We have NOP (no operation) synchronous function `common.emptiness` but need a NOP for asynchronous callback-last/error-first:
```
common.nop = (callback) => {
  callback(null);
}
```

**Comment by DzyubSpirit** [comment]
`metasync.fp.of` with no argument does the same.

**Comment by tshemsedinov** [comment]
@DzyubSpirit it use more closures and calls, we need minimal pass-through function.
Implemented in e3a9b19425019ab97500f1750f36bf674d8433fd
